### ISSUE TITLE
# Dewin(ster) // Review

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/reviews-2018-2019#1]
@dvberkel
I would like to receive an review for the following assignments:

- [x] [sorting-assignment-Dewinster](https://github.com/HAN-ASD-DT/sorting-assignment-Dewinster)
- [x] [tm-assignment-Dewinster](https://github.com/HAN-ASD-DT/tm-assignment-Dewinster)
- [x] [elm-assignment-Dewinster](https://github.com/HAN-ASD-DT/elm-assignment-Dewinster)
- [x] [elm-architecture-assignment-Dewinster](https://github.com/HAN-ASD-DT/elm-architecture-assignment-Dewinster)
- [x] [complexity-assignment-Dewinster](https://github.com/HAN-ASD-DT/complexity-assignment-Dewinster)
- [x] [rsa-assignment-Dewinster](https://github.com/HAN-ASD-DT/rsa-assignment-Dewinster)
- [x] [trolley-problem-assignment-Dewinster](https://github.com/HAN-ASD-DT/trolley-problem-assignment-Dewinster)
- [x] [kata-assignment-Dewinster](https://github.com/HAN-ASD-DT/kata-assignment-Dewinster)
- [ ] [Casus opdracht tussentijdse review](https://gitlab.com/AR-Sudoku-Solver/Sudoku-Solver-iOS)

**Comment by dvberkel** [comment]
@Dewinster could you transform all above names in actual links. This will speed up the process of reviewing.

**Comment by Dewinster** [comment]
- [ ] [sorting-assignment-Dewinster](https://github.com/HAN-ASD-DT/sorting-assignment-Dewinster)
- [ ] [tm-assignment-Dewinster](https://github.com/HAN-ASD-DT/tm-assignment-Dewinster)
- [ ] [elm-assignment-Dewinster](https://github.com/HAN-ASD-DT/elm-assignment-Dewinster)
- [ ] [elm-architecture-assignment-Dewinster](https://github.com/HAN-ASD-DT/elm-assignment-Dewinster)
- [ ] [complexity-assignment-Dewinster](https://github.com/HAN-ASD-DT/complexity-assignment-Dewinster)
- [ ] [rsa-assignment-Dewinster](https://github.com/HAN-ASD-DT/rsa-assignment-Dewinster)
- [ ] [trolley-problem-assignment-Dewinster](https://github.com/HAN-ASD-DT/trolley-problem-assignment-Dewinster)
- [ ] [kata-assignment-Dewinster](https://github.com/HAN-ASD-DT/kata-assignment-Dewinster)
- [ ] [Casus opdracht tussentijdse review](https://gitlab.com/AR-Sudoku-Solver/Sudoku-Solver-iOS)

**Comment by Dewinster** [comment]
@dvberkel 
Resolved all open issues.
Could you please continue the review process?

**Comment by dvberkel** [comment]
If you have resolved all open issues to your satisfaction you are all set.

I will take a look at the project.
