### ISSUE TITLE
# dcswitzer - Review Assignments

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/reviews-2018-2019#2]
@dvberkel
I would like to receive an review for the following assignments:

- [x] https://github.com/HAN-ASD-DT/sorting-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/tm-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/elm-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/elm-architecture-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/complexity-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/trees-assignment-dcswitzer
- [x] https://github.com/HAN-ASD-DT/rsa-assignment-dcswitzer

**Comment by dcswitzer** [comment]
@dvberkel 
See the list below for the links to the actual repositories. 

- [ ] https://github.com/HAN-ASD-DT/sorting-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/tm-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/elm-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/elm-architecture-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/complexity-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/trees-assignment-dcswitzer
- [ ] https://github.com/HAN-ASD-DT/rsa-assignment-dcswitzer

**Comment by dvberkel** [comment]
This looks good. You made very good progress I have made some issues, but that is mostly to clarify some fine points
