### ISSUE TITLE
Reviews Ties Baltissen

### ISSUE THREAD

**Issue by Skudoku** [HAN-ASD-DT/reviews-2018-2019#3]
- [x] [elm-assignment-Skudoku](https://github.com/HAN-ASD-DT/elm-assignment-Skudoku)
- [x] [rsa-assignment-Skudoku](https://github.com/HAN-ASD-DT/rsa-assignment-Skudoku)
- [x] [tm-assignment-Skudoku](https://github.com/HAN-ASD-DT/tm-assignment-Skudoku)
- [x] [elm-architecture-assignment-Skudoku](https://github.com/HAN-ASD-DT/elm-architecture-assignment-skudoku)
- [x] [sorting-assignment-Skudoku](https://github.com/HAN-ASD-DT/sorting-assignment-Skudoku)
- [x] [Code Kata's](https://github.com/Skudoku/Code-Katas-Ties)

**Comment by dvberkel** [comment]
I have created some issues in the corresponding assignments. Take a look at them
