### ISSUE TITLE
Review Luuk Verberkt

### ISSUE THREAD

**Issue by luukverberkt** [HAN-ASD-DT/reviews-2018-2019#4]
@dvberkel
I would like to receive an review for the following assignments:
* [x] https://github.com/HAN-ASD-DT/sorting-assignment-luukverberkt 
* [x] https://github.com/HAN-ASD-DT/tm-assignment-luukverberkt
* [x] https://github.com/HAN-ASD-DT/elm-assignment-luukverberkt
* [x] https://github.com/HAN-ASD-DT/trees-assignment-luukverberkt
* [x] https://github.com/HAN-ASD-DT/complexity-assignment-luukverberkt
* [x] https://github.com/HAN-ASD-DT/rsa-assignment-luukverberkt

**Comment by Skudoku** [comment]
@luukverberkt  Could you transform the names of the repositories to actual links? This will speed up the review process.

**Comment by Skudoku** [comment]
@luukverberkt pls respond

**Comment by luukverberkt** [comment]
@Skudoku  done.

**Comment by dvberkel** [comment]
I have opened some issues in the corresponding repositories. If you could review them.

**Comment by dvberkel** [comment]
When you resolve the issues, in anyway you see fit, you are done.

There will be an assessment in which we will go over your work once again, see how you feel about them, and where you will pass the class.
