### ISSUE TITLE
Review Bjorn Voesten

### ISSUE THREAD

**Issue by bjornvoesten** [HAN-ASD-DT/reviews-2018-2019#5]
@dvberkel Zou jij de volgende opdrachten welke een link hebben na willen nakijken?

- [x] [Sorting in The Desert](https://github.com/HAN-ASD-DT/sorting-assignment-bjornvoesten)
- [x] [Intro into Elm](https://github.com/HAN-ASD-DT/elm-assignment-bjornvoesten)
- [x] [Program a Turing Machine](https://github.com/HAN-ASD-DT/tm-assignment-bjornvoesten)
- [x] [Code Katas](https://github.com/HAN-ASD-DT/katas-bjornvoesten/blob/master/README.md)
- [x] [Diving deeper into Elm](https://github.com/HAN-ASD-DT/elm-architecture-assignment-bjornvoesten)
- [x] [Forest Full of Tees](https://github.com/HAN-ASD-DT/trees-assignment-bjornvoesten)
- [x] [Message in a Bottle](https://github.com/HAN-ASD-DT/rsa-assignment-bjornvoesten)
- [x] [Trolley Problem](https://github.com/HAN-ASD-DT/trolley-problem-assignment-bjornvoesten)

**Comment by bjornvoesten** [comment]
De opdrachten zonder link zal ik een volgende keer laten nakijken.

**Comment by dvberkel** [comment]
Ik heb naar jouw opgave gekeken. ik heb enkele issues aangemaakt. Zou jij daar nog een antwoord op willen geven?

Ik laat het issue nog even open zodat ik nog naar de andere opgave kan kijken wanneer daar een link bij is.

**Comment by bjornvoesten** [comment]
@dvberkel Ik heb hierbij een 3 tal katas toegevoegd onder [Code Katas](https://github.com/HAN-ASD-DT/katas-bjornvoesten/blob/master/README.md). Zou jij deze willen beoordelen?
