### ISSUE TITLE
Review Vincent 

### ISSUE THREAD

**Issue by vinnie1234** [HAN-ASD-DT/reviews-2018-2019#6]
@dvberkel Kan je de volgende opdrachten beoordelen?

- [x] [elm-assignment-vinnie1234](https://github.com/HAN-ASD-DT/elm-assignment-vinnie1234)
- [x] [sorting-assignment-vinnie1234](https://github.com/HAN-ASD-DT/sorting-assignment-vinnie1234)
- [x] [tm-assignment-vinnie1234](https://github.com/HAN-ASD-DT/tm-assignment-vinnie1234)
- [x] [complexity-assignment-vinnie1234](https://github.com/HAN-ASD-DT/complexity-assignment-vinnie1234)
- [x] [elm-architecture-assignment-vinnie1234](https://github.com/HAN-ASD-DT/elm-architecture-assignment-vinnie1234)
- [x] [trolley-problem-assignment-vinnie1234](https://github.com/HAN-ASD-DT/trolley-problem-assignment-vinnie1234)

**Comment by dvberkel** [comment]
Ik heb naar jouw opgave gekeken. Er staan nog een aantal issues open. Zou jij daar naar willen kijken?
